Repository dakshshah96/awesome-startup-credits, pull requests merged in 2019-02, with the labels that each got.

#4 Add Amplitude to analytics section.
  README.md
Labels: needs-review

#8 Add Edge Computing as a new category and StackPath Propel Program
  README.md
Labels: new-addition

#7 Add CleverCloud to CloudComputing
  README.md
Labels: needs-review, new-addition
